# Generated by Django 4.2.10 on 2024-08-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schedules_date_alter_schedules_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='summary',
            field=models.CharField(blank=True, default='No Summary', max_length=300, null=True),
        ),
    ]
